version: '3.8'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stats/stats-server
    image: stats-server_image
    container_name: stats-server_container
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090

  stats-db:
    ports:
      - "6541:5432"
    image: postgres:14-alpine
    container_name: stats-db_container
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


  ewm:
    build: main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5431/ewm-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-db:
    ports:
      - "6543:5431"
    image: postgres:14-alpine
    container_name: ewm-db-container
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test