version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stats/stats-server
    image: stats-server_image
    container_name: stats-server_container
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090

  stats-db:
    ports:
      - "6541:5432"
    image: postgres:14-alpine
    container_name: stats-db_container
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
